Revert "Workaround NoClassDefFoundError: org/codehaus/plexus/util/StringUtils https://github.com/mojohaus/keytool/issues/57"
This reverts commit 90b480b8edf14c10a7da4d945ec2c448de03e7e7.